BibliotecaVirtual/Controllers/LibroController.cs
using BibliotecaVirtual.Common.Libro;
using BibliotecaVirtual.Helpers;
using BibliotecaVirtual.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BibliotecaVirtual.Controllers
{
    public class LibroController : Controller
    {
        public LibroService _LibroService;

        public LibroController(LibroService _LibroService)
        {
            this._LibroService = _LibroService;
        }
        // GET: Libro
        public ActionResult Index()
        {
            IEnumerable<LibroListViewModel> _ListViewModel = _LibroService.GetAll();
            return View(_ListViewModel);
        }

        [HttpGet]
        public ActionResult Create()
        {
            LibroCreateViewModel model = new LibroCreateViewModel();            
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(LibroCreateViewModel model)
        {
            if (model.file.ContentLength > (2 * 1024 * 1024))
            {
                return View();
            }

            if (!(model.file.ContentType == "image/jpeg" || model.file.ContentType == "image/gif"))
            {
                return View();
            }

            byte[] data = new byte[model.file.ContentLength];
            model.file.InputStream.Read(data, 0, model.file.ContentLength);
            model.Imagen = data;            
            
            if (_LibroService.Create(model) > 0)
                TempData["LibroCreateSuccess"] = "Se Registro Correctamente";
            else
                TempData["LibroCreateError"] = "No se Registro";

            return RedirectToAction("index");
        }


        public ActionResult Delete(int id)
        {
            if(_LibroService.Delete(id)>0)
                TempData["LibroDeleteSuccess"] = "Se Elimino Correctamente";
            else
                TempData["LibroDeleteError"] = "No se Elimino";

            return RedirectToAction("index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            LibroEditViewModel _LibroEditViewModel = _LibroService.GetById(id);
            return View(_LibroEditViewModel);
        }

        public ActionResult Edit(LibroEditViewModel model)
        {
            if (_LibroService.Edit(model) > 0)
                TempData["LibroEditSuccess"] = "Se Actualizo Correctamente";
            else
                TempData["LibroEditError"] = "No se Actualizo";

            return RedirectToAction("index");
        }

        public ActionResult Details(int id)
        {
            LibroDetailViewModel _LibroDetailViewModel = _LibroService.GetDetail(id);
            return View(_LibroDetailViewModel);
        }
    }
}

BibliotecaVirtual/Views/Libro/Create.cshtml
@model BibliotecaVirtual.Common.Libro.LibroCreateViewModel


@{
    ViewBag.Title = "Crear Libro";
}

<h2>Nuevo Libro</h2>


@using (Html.BeginForm("Create", "Libro", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Editorial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Editorial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Editorial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Area, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Area, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Area, "", new { @class = "text-danger" })
            </div>
        </div>

       <div class="form-group">
            <label class="control-label col-md-2">Imagen</label>
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.file, new { @type = "file", @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BibliotecaVirtual/Views/Libro/Details.cshtml
@model BibliotecaVirtual.Common.Libro.LibroDetailViewModel

@{
    ViewBag.Title = "Detalle";
}

<h2>Detalle Del Libro</h2>

<div>    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nombre_autor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre_autor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.genero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.genero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.categoriaid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoriaid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cantidad)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id  }) |
    @Html.ActionLink("Regresar", "Index")
</p>

BibliotecaVirtual/Views/Libro/Edit.cshtml
@model BibliotecaVirtual.Common.Libro.LibroEditViewModel

@{
    ViewBag.Title = "Editar Libro";
}

<h2>Editar Libro</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nombre_autor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre_autor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre_autor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.genero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.genero, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.genero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.categoriaid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.categoriaid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.categoriaid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BibliotecaVirtual/Views/Libro/Index.cshtml
@model IEnumerable<BibliotecaVirtual.Common.Libro.LibroListViewModel>

@{
    ViewBag.Title = "Libros";
}

<h2>Mantenimiento de Libros</h2>

<p>
    @Html.ActionLink("Nuevo Libro", "Create")  
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Titulo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Editorial)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Area)
        </th>       
        @*<th>
            @Html.DisplayNameFor(model => model.Imagen)
        </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Editorial)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Area)
            </td>           
            @*<td>
                <img src="data:image/png;base64,@Convert.ToBase64String(item.Imagen, 0, item.Imagen.Length)" height="50" width="50"/>
            </td>*@
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Detalle", "Details", new { id = item.Id }) |
                @Html.ActionLink("Eliminar", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

<script type="text/javascript">
    $(function () {
        @if (TempData.ContainsKey("LibroCreateSuccess"))
         {
             <text>
        $(function () {
            toastr.success('@TempData["LibroCreateSuccess"]');
            @{TempData.Remove("LibroCreateSuccess");}
        })
        </text>
         }
        else if (TempData.ContainsKey("LibroCreateError"))
         {
            <text>
        $(function () {
            toastr.error('@TempData["LibroCreateError"]');
            @{TempData.Remove("LibroCreateError");}
        })
        </text>
         }
        else if (TempData.ContainsKey("LibroDeleteSuccess"))
        {
            <text>
        $(function () {
            toastr.success('@TempData["LibroDeleteSuccess"]');
            @{TempData.Remove("LibroDeleteSuccess");}
        })
            </text>
        }
        else if (TempData.ContainsKey("LibroDeleteError"))
        {
            <text>
            $(function () {
                toastr.error('@TempData["LibroDeleteError"]');
                @{TempData.Remove("LibroDeleteError");}
            })
            </text>
        }
        else if (TempData.ContainsKey("LibroEditSuccess"))
        {
            <text>
            $(function () {
                toastr.success('@TempData["LibroEditSuccess"]');
                @{TempData.Remove("LibroEditSuccess");}
            })
            </text>
        }
        else if (TempData.ContainsKey("LibroEditError"))
        {
            <text>
            $(function () {
                toastr.error('@TempData["LibroEditError"]');
                @{TempData.Remove("LibroEditError");}
            })
            </text>
        }

    })
</script>